spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 配置mapper文件的位置
  mapper-locations: classpath:org/example/mapper/*.xml

  # 配置别名包扫描路径，自动扫描别名
  type-aliases-package: org.example.entity

  # 配置MyBatis的configuration
  configuration:
    # 开启驼峰命名自动映射，即将数据库中的下划线命名自动转换为Java对象的驼峰命名
    map-underscore-to-camel-case: true
    # 配置日志实现，可选值：STDOUT_LOGGING, FILE, SLF4J, LOG4J等
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 其他MyBatis配置...
  config-location: mybatis/mybatis-config.xml

#  # 配置MyBatis-Plus（如果你使用的是MyBatis-Plus）
#  # 注意：以下配置是MyBatis-Plus特有的
#  plus:
#    # 全局配置ID生成策略
#    global-config:
#      db-config:
#        id-type: AUTO
#        # 其他数据库配置...
#    # 配置Mapper扫描路径
#    mapper-locations: classpath:org.example.mapper/**/*.xml
#    # 类型别名包扫描
#    type-aliases-package: org.example.entity
#    # 其他MyBatis-Plus配置...